Update git_build.yml

diff --git a/.github/workflows/git_build.yml b/.github/workflows/git_build.yml
--- a/.github/workflows/git_build.yml
+++ b/.github/workflows/git_build.yml
@@ -43,7 +43,7 @@ jobs:
         run: |
           mkdir -p git-static
           sudo apt update &> /dev/null
-          sudo apt install -y git make autoconf re2c libexpat1-dev asciidoc libz-dev gettext curl libtool libtool-bin zlib1g-dev libcurl4-openssl-dev libxml2-dev libyaml-dev libgmp-dev libzip-dev libssl-dev &> /dev/null
+          sudo apt install -y git make autoconf build-essentials re2c libexpat1-dev asciidoc libz-dev gettext curl libtool libtool-bin zlib1g-dev libcurl4-openssl-dev libxml2-dev libyaml-dev libgmp-dev libzip-dev libssl-dev &> /dev/null
 
           DIR="$(pwd)"
           BASE_BUILD_DIR="$DIR/install_data"
@@ -86,7 +86,29 @@ jobs:
               export CPP="$TOOLCHAIN_PREFIX-cpp"
               export LD="$TOOLCHAIN_PREFIX-ld"
           fi
-          
+          echo "#include <stdio.h>" > test.c
+          echo "int main(void){" >> test.c
+          echo "printf(\"Hello world\n\");" >> test.c
+          echo "return 0;" >> test.c
+          echo "}" >> test.c
+          $CC -march=$march $CFLAGS -o test test.c >> "$DIR/install.log" 2>&1
+          if [ $? -eq 0 ]; then
+            CFLAGS="-march=$march -fno-gcse $CFLAGS"
+          fi
+          CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" $CC -fsanitize=$FSANITIZE_OPTIONS -o asan-test test.c  && \
+              chmod +x asan-test >> "$DIR/install.log" 2>&1 && \
+              ./asan-test >> "$DIR/install.log" 2>&1 && \
+              rm asan-test >> "$DIR/install.log" 2>&1
+          #if [ $? -ne 0 ]; then
+          #  echo "[ERROR] One or more sanitizers are not working. Check install.log for details."
+          #  exit 1
+          #else
+          #  echo "[INFO] All selected sanitizers are working"
+          #fi
+
+          m test.* >> "$DIR/install.log" 2>&1
+          rm test >> "$DIR/install.log" 2>&1
+
           export CC="$CC"
           export CXX="$CXX"
           export CFLAGS="-O2 -fPIC $CFLAGS"
@@ -110,7 +132,7 @@ jobs:
 
           echo DL git repo
           
-          curl https://mirrors.kernel.org/pub/software/scm/git/git-2.41.0.tar.gz | tar xvz
+          curl https://mirrors.kernel.org/pub/software/scm/git/git-2.41.0.tar.gz | tar xvj
           cd git-2.41.0
           ./configure --prefix=$DIR/git-static NO_OPENSSL=1 NO_CURL=1
           make -j 1 install
